# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'history_grade_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(319, 56)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 301, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.username_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.username_label.setAlignment(QtCore.Qt.AlignCenter)
        self.username_label.setObjectName("username_label")
        self.horizontalLayout.addWidget(self.username_label)
        self.datetime_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.datetime_label.setAlignment(QtCore.Qt.AlignCenter)
        self.datetime_label.setObjectName("datetime_label")
        self.horizontalLayout.addWidget(self.datetime_label)
        self.pushup_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.pushup_label.setAlignment(QtCore.Qt.AlignCenter)
        self.pushup_label.setObjectName("pushup_label")
        self.horizontalLayout.addWidget(self.pushup_label)
        self.pullup_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.pullup_label.setAlignment(QtCore.Qt.AlignCenter)
        self.pullup_label.setObjectName("pullup_label")
        self.horizontalLayout.addWidget(self.pullup_label)
        self.situp_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.situp_label.setAlignment(QtCore.Qt.AlignCenter)
        self.situp_label.setObjectName("situp_label")
        self.horizontalLayout.addWidget(self.situp_label)
        self.squat_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.squat_label.setAlignment(QtCore.Qt.AlignCenter)
        self.squat_label.setObjectName("squat_label")
        self.horizontalLayout.addWidget(self.squat_label)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.username_label.setText(_translate("Form", "aa"))
        self.datetime_label.setText(_translate("Form", "bb"))
        self.pushup_label.setText(_translate("Form", "cc"))
        self.pullup_label.setText(_translate("Form", "dd"))
        self.situp_label.setText(_translate("Form", "ee"))
        self.squat_label.setText(_translate("Form", "ff"))
