# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mediapipe_checksystem_t.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(890, 560)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 871, 501))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.name_label.setObjectName("name_label")
        self.horizontalLayout.addWidget(self.name_label)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.calculate_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.calculate_button.setObjectName("calculate_button")
        self.horizontalLayout.addWidget(self.calculate_button)
        self.open_video_folder_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.open_video_folder_button.setObjectName("open_video_folder_button")
        self.horizontalLayout.addWidget(self.open_video_folder_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.video_listWidget_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.video_listWidget_label.setAlignment(QtCore.Qt.AlignCenter)
        self.video_listWidget_label.setObjectName("video_listWidget_label")
        self.verticalLayout_3.addWidget(self.video_listWidget_label)
        self.video_listWidget = QtWidgets.QListWidget(self.horizontalLayoutWidget_2)
        self.video_listWidget.setObjectName("video_listWidget")
        self.verticalLayout_3.addWidget(self.video_listWidget)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.history_grade_listWidget_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.history_grade_listWidget_label.setAlignment(QtCore.Qt.AlignCenter)
        self.history_grade_listWidget_label.setObjectName("history_grade_listWidget_label")
        self.verticalLayout.addWidget(self.history_grade_listWidget_label)
        self.history_grade_listWidget = QtWidgets.QListWidget(self.horizontalLayoutWidget_2)
        self.history_grade_listWidget.setObjectName("history_grade_listWidget")
        self.verticalLayout.addWidget(self.history_grade_listWidget)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 890, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "教师端"))
        self.name_label.setText(_translate("MainWindow", "xxx"))
        self.label_2.setText(_translate("MainWindow", "你好！"))
        self.calculate_button.setText(_translate("MainWindow", "开始统计"))
        self.open_video_folder_button.setText(_translate("MainWindow", "打开视频录像文件夹"))
        self.video_listWidget_label.setText(_translate("MainWindow", "视频录像"))
        self.history_grade_listWidget_label.setText(_translate("MainWindow", "学生成绩"))
